create table usuarios (id int8 generated by default as identity, cpf varchar(255), login varchar(255), senha varchar(255), primary key (id));
create table usuarios (id int8 generated by default as identity, cpf varchar(255), login varchar(255), senha varchar(255), primary key (id));
create table usuarios (id int8 generated by default as identity, cpf varchar(255), login varchar(255), senha varchar(255), primary key (id));
create table usuarios (id int8 generated by default as identity, cpf varchar(255), login varchar(255), senha varchar(255), primary key (id));
create table usuarios (id int8 generated by default as identity, cpf varchar(255), login varchar(255), senha varchar(255), primary key (id));
create table usuarios (id int8 generated by default as identity, cpf varchar(255), login varchar(255), senha varchar(255), primary key (id));
